Develop
olga-bylnova/angular-app pull request #1
Opened 2024-08-11 13:52 UTC by olga-bylnova

2024-09-04 11:37 UTC, ShkrobNastya requested changes

2024-09-04 11:37 UTC, ShkrobNastya commented on angular.json
please, add to README how to start project (BE part)

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/auth-page/auth-page.component.html
> +                <div *ngIf="authForm.get('password')?.errors?.['required']">Password is required.</div>
if in file value used more > 2, then we can use getter like this:

```
get password() {
    return this.authForm.get('password');
  }
```

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/auth-page/auth-page.component.html
> +    </a>
do we need a link here?

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/cart-page/cart-page.component.ts
> +        console.log(`Cart item with id ${cartItemId} deleted`);
console.log mostly used for errors messages, it's not needed here

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/directive/stock-label.directive.ts
> +      this.el.nativeElement.textContent = text;
please, redo, using Renderer2 service

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/model/product.ts
> +    reviews: Review[];
you can'r be sure, that you will receive all data, please do fields optional

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/product-details/product-details.component.ts
> +  }
in angular we work with Observables in 99.9% cases, RxJs gives us many opportunities to manipulate data, also it provide lazy execution and cancellation (unsubscribe)

regarding rendered data, good practice is to use 
*ngIf="product$ | async as product" in html file

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/service/product.service.ts
> +  }
in angular we work with streaming data, it gives us many ways of manipulation with it
so in 99.9%  cases we use Observables

2024-09-04 11:37 UTC, ShkrobNastya commented on angular.json
>    }
please, redo project structure  (core module in scope of this project not required)
you can use this example 
![image](https://github.com/user-attachments/assets/1927d072-05e1-4b4f-ada1-5c2944a78ac4)

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/cart-page/cart-page.component.html
> +<table *ngIf="cartItems.length > 0">
you can use here if else

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/cart-page/cart-page.component.html
> +<table *ngIf="cartItems.length > 0">
in html file we always have one root tag, you can also use ng-container

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/cart-page/cart-page.component.html
> +<table *ngIf="cartItems.length > 0">
please, fix it everywhere

2024-09-04 11:37 UTC, ShkrobNastya commented on angular.json
>    }
also database in data folder: data/db.json folder

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/product-details/product-details.component.ts
> +  }
please, replace Promise to Observable everywhere in the project

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/service/cart.service.ts
> +    return cartItems.length > 0 ? cartItems[0] : undefined;
redo to Observable

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/service/cart.service.ts
> +      );
all if ...else logic should be in component.ts files 
if it's update cart item function - then update cart item, for create cart item you need to add another function

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/service/filter.service.ts
> +      hasReviews: params['hasReviews'] === 'true'
you can't be sure what values you will receive from BE, create an object (like BE response) and work with it

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/service/product.service.ts
> +      }
never do subscription immediately, you're losing all benefits of using RxJs
please fix it everywhere in the project

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/service/product.service.ts
> +    ['ratingTo', 'rating.rate_lte']
this values should be in object that I mentioned before (like BE response)

2024-09-04 11:37 UTC, ShkrobNastya commented on src/app/service/product.service.ts
here I see you united two types of services, let me clarify:
in component.ts we add logic, that responds to user actions, like - delete, update, add, submit, etc
in general services we add logic that somehow manipulate with data, transforms it
in data-services we make requests
example of data-service:
![image](https://github.com/user-attachments/assets/c3ae5d34-cc3a-4bfa-8f97-1f19aade9a43)

2024-09-04 11:39 UTC, ShkrobNastya commented
please, firstly pay attention on comments regarding:
1. Promises & Observables
2. services difference(last comment)
3. project structure

2024-09-24 22:04 UTC, ShkrobNastya commented on angular.json
done

2024-09-24 22:04 UTC, ShkrobNastya commented on angular.json
>    }
done

2024-09-24 22:05 UTC, ShkrobNastya commented on src/app/service/product.service.ts
done

2024-09-24 22:06 UTC, ShkrobNastya commented on src/app/product-details/product-details.component.ts
> +  }
done

2024-09-24 22:06 UTC, ShkrobNastya commented on src/app/service/product.service.ts
> +  }
done

2024-09-24 22:07 UTC, ShkrobNastya commented on src/app/auth-page/auth-page.component.html
> +                <div *ngIf="authForm.get('password')?.errors?.['required']">Password is required.</div>
done

2024-09-24 22:07 UTC, ShkrobNastya commented on src/app/auth-page/auth-page.component.html
> +    </a>
done

2024-09-24 22:07 UTC, ShkrobNastya commented on src/app/cart-page/cart-page.component.ts
> +        console.log(`Cart item with id ${cartItemId} deleted`);
done

2024-09-24 22:08 UTC, ShkrobNastya commented on src/app/directive/stock-label.directive.ts
> +      this.el.nativeElement.textContent = text;
done

2024-09-24 22:09 UTC, ShkrobNastya commented on src/app/cart-page/cart-page.component.html
> +<table *ngIf="cartItems.length > 0">
done

2024-09-24 22:09 UTC, ShkrobNastya commented on src/app/cart-page/cart-page.component.html
> +<table *ngIf="cartItems.length > 0">
done

2024-09-24 22:09 UTC, ShkrobNastya commented on src/app/service/cart.service.ts
> +    return cartItems.length > 0 ? cartItems[0] : undefined;
done

2024-09-24 22:10 UTC, ShkrobNastya commented on src/app/service/cart.service.ts
> +      );
done

2024-09-24 22:11 UTC, ShkrobNastya commented on src/app/service/product.service.ts
> +      }
done

2024-09-24 22:13 UTC, ShkrobNastya commented on src/app/service/product.service.ts
> +    ['ratingTo', 'rating.rate_lte']
done

2024-09-25 21:13 UTC, ShkrobNastya requested changes

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/auth/pages/auth-page/auth-page.component.ts
> +    event.preventDefault();
Is it necessary here?

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/auth/services/auth.service.ts
> +        if (this.isArrayEmpty(existingUser)) {
in (if close) usually first case is true, also isArrayEmpty function not necessary, you can use if(existingUser.length)

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/components/add-to-cart-button/add-to-cart-button.component.ts
> +    productCountButtons?.classList.add('product-count-section-visible');
in angular we have ngClass or ngStyle, please, redo using this

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/components/add-to-cart-button/add-to-cart-button.component.html
> +        <button class="minus-button" (click)="changeProductCount($event)">
better to create 2 different functions: increment and decrement product count

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/components/add-to-cart-button/add-to-cart-button.component.ts
> +  }
is this code block required?

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/pages/home/home.component.ts
> +    });
constructor mostly used for services injection, super() function call, and sometimes form initialisation

this subscription better to move in ngOnInit

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/components/add-to-cart-button/add-to-cart-button.component.html
I have 6 items of this product in cart, so on homepage it also should be 6(instead of "add to cart")
![image](https://github.com/user-attachments/assets/22fafd82-1e90-4fb0-8feb-7b61b47b37a7)

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/components/filter/filter.component.html
in url shoud be only actual filters, inStock and hasReviews are default 
![image](https://github.com/user-attachments/assets/355a385c-2ce7-4298-8628-4e71eddadac6)

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/components/filter/filter.component.html
user can't be able to input negative numbers and rating > 5
![image](https://github.com/user-attachments/assets/2ceef7c4-ded2-46ec-9123-0443923f6d76)

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/components/filter/filter.component.html
if filter is removed, it should be removed from url too

![image](https://github.com/user-attachments/assets/77ee12e0-4882-48c0-8d8a-22b3991b922e)

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/components/filter/filter.component.html
when I click on back or forward values on filter form not added

![image](https://github.com/user-attachments/assets/8e22040b-9858-4152-8fdf-8201cab60ac6)

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/pages/product-details/product-details.component.html
error when I click on add to cart
![image](https://github.com/user-attachments/assets/c0ab2fd9-6c61-4313-9bdf-b972ed0ad8ad)

2024-09-25 21:13 UTC, ShkrobNastya commented on src/app/products/components/filter/filter.component.html
apply filter button is active when no filters added
![image](https://github.com/user-attachments/assets/ec2297af-7fb6-403e-8c28-fa214d8db9e1)

2024-09-25 21:15 UTC, ShkrobNastya commented on src/app/products/components/filter/filter.component.html
please, fix view when no products found 
![image](https://github.com/user-attachments/assets/679a1be2-d661-47e9-9c3b-259db1203cc0)

2024-10-14 20:09 UTC, ShkrobNastya commented on src/app/auth/services/auth.service.ts
> +        if (this.isArrayEmpty(existingUser)) {
done

2024-10-14 20:10 UTC, ShkrobNastya commented on src/app/products/components/add-to-cart-button/add-to-cart-button.component.ts
> +    productCountButtons?.classList.add('product-count-section-visible');
done

2024-10-14 20:11 UTC, ShkrobNastya commented on src/app/products/components/add-to-cart-button/add-to-cart-button.component.html
> +        <button class="minus-button" (click)="changeProductCount($event)">
done

2024-10-14 20:11 UTC, ShkrobNastya commented on src/app/products/components/add-to-cart-button/add-to-cart-button.component.ts
> +  }
done

2024-10-14 20:12 UTC, ShkrobNastya commented on src/app/products/pages/home/home.component.ts
> +    });
done

2024-10-14 20:15 UTC, ShkrobNastya commented on src/app/products/components/add-to-cart-button/add-to-cart-button.component.html
done

2024-10-14 20:37 UTC, ShkrobNastya approved these changes

2024-10-14 20:37 UTC, ShkrobNastya commented on src/app/products/components/filter/filter.component.html
done

2024-10-14 20:37 UTC, ShkrobNastya commented on src/app/products/components/filter/filter.component.html
done

2024-10-14 20:37 UTC, ShkrobNastya commented on src/app/products/pages/product-details/product-details.component.html
done

2024-10-14 22:02 UTC, olga-bylnova commented
is this pr approved? can i merge the changes?

2024-10-15 12:29 UTC, merged